/* The plan
- When your route or web adress changes in a Single Page App or otherwise, ask an LLM if the web page is a product list page, a product detail page, or neither.
- Whatever is sent to is-recalled-backend must have productName and clientProductId of the overall page for now.
-- clientId is generated by the frontend and is a reliable way for the client to find the response for each product, since the list of products may not come back in the order they were sent.
- If it's a product list page, get the LLM to extract a list of the products on the page and send to is-recalled-backend. 
- If it's product details page, mark that product as primary and still send it in a list of products. E-commerce sites almost always have recommendations for other products these days on product details pages, so all the other products can be extracted, added to the list of the products on the page and sent to is-recalled-backend.
- So for example, request body should be:
{
    "url": "https://www.example.com/product/1234567890",
    "pageType": "PRODUCT_LIST || PRODUCT_DETAILS"
    "products": [
        {
            "productName": "Product 1",
            "clientProductId": "1234567890"
        },
        {
            "productName": "Product 2",
            "clientProductId": "1234567891"
            "isPrimary": true
        },
    ]
}
- If any recall matches are found:
-- Find and highlight the product's name on the page. See if you can get classNames from the LLM to highlight as well.
-- Make the extension itself show an alert of some sort. I'm assuming it will show in the toolbar, just like Redux Devtools shows there by default.
- If multiple items on the site have recalls, how do I link the user to isrecalled.com for each one?
-- After highlighting an element on the page, I could also add an onClick listener or a link that leads the user to a RecallDetailsPage on isrecalled.com.
-- I could also make the extension have some HTML or even React that it can use to render a paginatable and searchable list of recalls found. A structure of this can be:

        Search box
        |______________________|

            Product Name
            - Recall one: circular logo of source, inscribed in red because of severity, short description of recall reason.
            - Recall two: circular logo of source, inscribed in yellow because of severity, short description of recall reason.

        << < 1  2  3  4 > >>
*/

// **********************
// Start of Reading Time Plugin
// **********************

function renderReadingTime(article: HTMLElement | null) {
  // If we weren't provided an article, we don't need to render anything.
  if (!article) {
    return;
  }

  const text = article.textContent;
  const wordMatchRegExp = /[^\s]+/g; // Regular expression
  const words = text.matchAll(wordMatchRegExp);
  // matchAll returns an iterator, convert to array to get word count
  const wordCount = [...words].length;
  const readingTime = Math.round(wordCount / 200);
  const badge = document.createElement("p");
  // Use the same styling as the publish information in an article's header
  badge.classList.add("color-secondary-text", "type--caption");
  badge.textContent = `⏱️ ${readingTime} min read`;
  //   badge.style.color = "red";
  badge.style.fontSize = "16px";
  badge.style.fontStyle = "italic";

  // Support for API reference docs
  const heading = article.querySelector("h1");
  // Support for article docs with date
  const date = article.querySelector("time")?.parentElement;
  if (!date && !heading) {
    return;
  }

  (date ?? heading)?.insertAdjacentElement("afterend", badge);
}

renderReadingTime(document.querySelector("article"));

const observer = new MutationObserver((mutations) => {
  for (const mutation of mutations) {
    // If a new article was added.
    for (const node of mutation.addedNodes) {
      if (node instanceof HTMLElement && node.tagName === "ARTICLE") {
        // Render the reading time for this particular article.
        renderReadingTime(node);
      }
    }
  }
});

// https://developer.chrome.com/ is a SPA (Single Page Application) so can
// update the address bar and render new content without reloading. Our content
// script won't be reinjected when this happens, so we need to watch for
// changes to the content.
const bodyNode = document.querySelector("body");
if (bodyNode) {
  observer.observe(bodyNode, {
    childList: true,
    subtree: true,
  });
}

// **********************
// End of Reading Time Plugin
// **********************

// Function to send HTML to service worker for cleaning
function sendHtmlToServiceWorker(html: string) {
  chrome.runtime.sendMessage(
    {
      action: "cleanHtml",
      html: html,
    },
    (response) => {
      console.log(
        "[sendHtmlToServiceWorker] Response from service worker:",
        response
      );
      if (response && response.success) {
        console.log("HTML cleaned and cached by service worker");
      }
    }
  );
}

// Only the content script is able to access the DOM
chrome.runtime.onConnect.addListener(function (port) {
  port.onMessage.addListener(function (msg) {
    // Send raw HTML to service worker for cleaning
    const html = document.body?.outerHTML;

    chrome.runtime.sendMessage(
      {
        action: "cleanHtml",
        html: html,
      },
      (response) => {
        if (response && response.success) {
          // Send cleaned content back through port
          port.postMessage({ contents: response.cleanedContent });
        } else {
          // Fallback to innerText if cleaning fails
          port.postMessage({ contents: document.body.innerText });
        }
      }
    );
  });
});

let htmlUpdateTimeout: ReturnType<typeof setTimeout> | null = null;

// Observe DOM changes and send updated HTML to service worker
const domObserver = new MutationObserver((mutations) => {
  // Debounce: only send after DOM settles
  if (htmlUpdateTimeout) {
    clearTimeout(htmlUpdateTimeout);
  }
  htmlUpdateTimeout = setTimeout(() => {
    const body = document.querySelector("body");
    if (body) {
      sendHtmlToServiceWorker(body.getHTML());
    }
  }, 100);

  // for (const mutation of mutations) {
  //   for (const node of mutation.addedNodes) {
  //     if (node instanceof Element) {
  //       sendHtmlToServiceWorker(node.outerHTML);
  //     }
  //   }
  // }
});

// Observe the existing observer's body node or create new observation
if (bodyNode) {
  domObserver.observe(bodyNode, {
    childList: true,
    subtree: true,
  });
}
