import "./estimate-reading-time";

/* The plan
- When your route or web adress changes in a Single Page App or otherwise, use various techniques to determine if the web page is a product list page, a product detail page, or neither.
- Whatever is sent to is-recalled-backend must at least have productName and cssSelector for now.
-- cssSelector is generated by the client and is a reliable way for the client to find the response for each product, since the list of products may not come back in the order they were sent.
- Extract a list of products. If you can determine that you're on a product details page and can determine the primary product, do so. E-commerce sites almost always have recommendations for other products these days on product details pages, so all the other products can be extracted, added to the list of the products on the page and sent to is-recalled-backend.
- So for example, request body should be:
{
    "url": "https://www.example.com/product/1234567890",
    "pageType": "PRODUCT_LIST || PRODUCT_DETAILS"
    "products": [
        {
            "productName": "Product 1",
            "cssSelector": "1234567890"
        },
        {
            "productName": "Product 2",
            "cssSelector": "1234567891"
            "isPrimary": true
        },
    ]
}

TBCL
- If any recall matches are found:
-- Find and highlight the product's name on the page. See if you can get classNames from the LLM to highlight as well.
-- Make the extension itself show an alert of some sort. I'm assuming it will show in the toolbar, just like Redux Devtools shows there by default.
- If multiple items on the site have recalls, how do I link the user to isrecalled.com for each one?
-- After highlighting an element on the page, I could also add an onClick listener or a link that leads the user to a RecallDetailsPage on isrecalled.com.
-- I could also make the extension have some HTML or even React that it can use to render a paginatable and searchable list of recalls found. A structure of this can be:

        Search box
        |______________________|

            Product Name
            - Recall one: circular logo of source, inscribed in red because of severity, short description of recall reason.
            - Recall two: circular logo of source, inscribed in yellow because of severity, short description of recall reason.

        << < 1  2  3  4 > >>
*/

const cleanHtmlInTheBackground = (html: string) => {
  chrome.runtime.sendMessage(
    {
      action: "cleanHtml",
      html,
    },
    (response) => {
      console.log(
        "[cleanHtmlInTheBackground] Response from service worker:",
        response
      );
    }
  );
};

let htmlUpdateTimeout: ReturnType<typeof setTimeout> | null = null;

const domObserver = new MutationObserver(() => {
  // Debounce: only process changes after DOM settles
  if (htmlUpdateTimeout) {
    clearTimeout(htmlUpdateTimeout);
  }

  htmlUpdateTimeout = setTimeout(() => {
    const body = document.querySelector("body");
    if (body) {
      cleanHtmlInTheBackground(body.getHTML());
    }
  }, 300);
});

const bodyNode = document.querySelector("body");

if (bodyNode) {
  domObserver.observe(bodyNode, {
    childList: true,
    subtree: true,
  });
}
